apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: training-deploy
  name: training-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: training-deploy
    spec:
      containers:
      - image: jenkins_job_docker_image:1.0
        name: jenkins-job-docker-image-nxkn9
        ports:
        - containerPort: 8000
        resources: {}
status: {}
