apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: training-deploy
  name: training-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: training-deploy
    spec:
      containers:
      - image: arun198628/new_training_image:1.0
        name: new-training-image-s76cc
        resources: {}
        volumeMounts:
                - name: envvol
                  mountPath: /etc/foo
                - name: pvcvol
                  mountPath: /etc/pvc_vol
      volumes:
              - name: envvol
                configMap:
                        name: training-cm
              - name: pvcvol
                persistentVolumeClaim:
                        claimName: training-pvc
status: {}
