apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: training-pvc
spec:
        accessModes:
                - ReadWriteMany
        storageClassName: normal
        resources:
                requests:
                        storage: 1G
