apiVersion: v1
kind: PersistentVolume
metadata:
        name: training-pv
spec:
        accessModes:
                - ReadWriteMany
        storageClassName: normal
        capacity:
                storage: 1G
        hostPath:
                path: /opt

